### ISSUE TITLE
psiblast warning message

### ISSUE THREAD

**Issue by zyh4482** [wasicse/Dispredict3.0#1]
My fasta file includes multiple transcripts. I test my data on the Docker image. 

But it generated many warning messages as below: 
```
Dataset Path: /data/ensembl/proteome_transcript.fasta
Output Path: /data/Dispredict3/output/
Loading models...
Extracting features from fldpnn...
Warning: [psiblast] lcl|Query_1 ENST00000332990: Warning: Composition-based score adjustment conditioned on sequence properties and unconditional composition-based score adjustment is not supported with PSSMs, resetting to default value of standard composition-based statistics 
Warning: [psiblast] lcl|Query_1 ENST00000361227: Warning: Composition-based score adjustment conditioned on sequence properties and unconditional composition-based score adjustment is not supported with PSSMs, resetting to default value of standard composition-based statistics 
....
....
....
```

Is this result harmful? How can I resolve it? 

Thank you.

**Comment by zyh4482** [comment]
A new issue occurs.

```
Loading ESM-1b model...
Killed
```
Is it due to low GPU RAM? Is there other workaround? 

My hardware list is as below:
Two AMD EPYC 7432
RAM: 256GB
GPU: NVIDIA GeForce RTX3060

**Comment by Fedeluppi** [comment]
I am also facing this issue:

`Loading ESM-1b model...
Killed`

**Comment by Fedeluppi** [comment]
> A new issue occurs.
> 
> ```
> Loading ESM-1b model...
> Killed
> ```
> 
> Is it due to low GPU RAM? Is there other workaround?
> 
> My hardware list is as below: Two AMD EPYC 7432 RAM: 256GB GPU: NVIDIA GeForce RTX3060

You can solve the issue by running the docker with more memory!

**Comment by wasicse** [comment]
> Warning: Composition-based score adjustment conditioned on sequence properties and unconditional composition-based score adjustment is not supported with PSSMs, resetting to default value of standard composition-based statistics 
> Warning: [psiblast] lcl|Query_1 ENST00000361227: Warning: Composition-based score adjustment conditioned on sequence properties and unconditional composition-based score adjustment is not supported with PSSMs, resetting to default value of standard composition-based statistics 
> ....

You can ignore the warning.
