### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)`

### ISSUE THREAD

**Issue by Fedeluppi** [wasicse/Dispredict3.0#2]
Hello,

I am encountering this issue and I am not really sure how to solve it. Can you help?

`(.venv) root@69a13bdef623:/opt/Dispredict3.0# python /opt/Dispredict3.0/script/Dispredict3.0.py -f "/opt/Dispredict3.0/example/sample.fasta" -o "/opt/Dispredict3.0/output/"
Dataset Path: /opt/Dispredict3.0/example/sample.fasta
Output Path: /opt/Dispredict3.0/output/
Loading models...
Extracting features from fldpnn...
Warning: [psiblast] lcl|Query_1 DP01096: Warning: Composition-based score adjustment conditioned on sequence properties and unconditional composition-based score adjustment is not supported with PSSMs, resetting to default value of standard composition-based statistics 
Warning: [psiblast] lcl|Query_1 P01034: Warning: Composition-based score adjustment conditioned on sequence properties and unconditional composition-based score adjustment is not supported with PSSMs, resetting to default value of standard composition-based statistics 
Warning: [psiblast] lcl|Query_1 P0DJI9: Warning: Composition-based score adjustment conditioned on sequence properties and unconditional composition-based score adjustment is not supported with PSSMs, resetting to default value of standard composition-based statistics 
Warning: [psiblast] lcl|Query_1 P61626: Warning: Composition-based score adjustment conditioned on sequence properties and unconditional composition-based score adjustment is not supported with PSSMs, resetting to default value of standard composition-based statistics 
./DisoComb.sh: line 119:   794 Illegal instruction     python3 Disnet.py ./tmp$number/$line.ttscore > ./tmp$number/$line.ttpreds
./DisoComb.sh: line 119:   812 Illegal instruction     python3 Disnet.py ./tmp$number/$line.ttscore > ./tmp$number/$line.ttpreds
./DisoComb.sh: line 119:   830 Illegal instruction     python3 Disnet.py ./tmp$number/$line.ttscore > ./tmp$number/$line.ttpreds
./DisoComb.sh: line 119:   848 Illegal instruction     python3 Disnet.py ./tmp$number/$line.ttscore > ./tmp$number/$line.ttpreds

Loading ESM-1b model...
Dispredict3.0 prediction started...
P61626
Sequence length:  148
Traceback (most recent call last):
  File "/opt/Dispredict3.0/script/Dispredict3.0.py", line 237, in <module>
    dispredict(options.fasta_filepath,options.output_path)
  File "/opt/Dispredict3.0/script/Dispredict3.0.py", line 168, in dispredict
    np_fld=np.hstack((np_fldscore,np_proba_pred))       
  File "<__array_function__ internals>", line 6, in hstack
  File "/opt/Dispredict3.0/.venv/lib/python3.7/site-packages/numpy/core/shape_base.py", line 346, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)`

Thanks!

**Comment by Fedeluppi** [comment]
I pulled the container as reported in the gitrepo: docker pull wasicse/dispredict3.0
Perhaps, there is a newer version that does not have the issue? Because on dockerHub seems that the upload of the docker happened 2 yrs ago but on github there are many more recents commits.

**Comment by wasicse** [comment]
I have just tested on https://www.gitpod.io/. The following commands works fine over there.

docker run -ti --name dispredict3.0  wasicse/dispredict3.0:latest
export PATH="/opt/poetry/bin:${PATH}"
source /opt/Dispredict3.0/.venv/bin/activate
python /opt/Dispredict3.0/script/Dispredict3.0.py -f "/opt/Dispredict3.0/example/sample.fasta" -o "/opt/Dispredict3.0/output/"

We also have a webserver https://bmll.cs.uno.edu.

**Comment by Fedeluppi** [comment]
Hello,

Thanks for answering!

I have just tried on GitPod and it works for me as well. I will keep investigating, do you think it plays any role that my system architecture is:
`Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64`
Because I have realized that if I build the container myself with the docker image it does not work.

` => ERROR [6/8] RUN pyenv install miniconda3-4.7.12 &&       pyenv global miniconda3-4.7.12 &&       curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 - &&       git clone https://github.com/wasicse/Dispredict3.0.git                                                                                                                                                                                   0.2s
------                                                                                                                                                                                                                                                                                                                                                                                                                                      
 > [6/8] RUN pyenv install miniconda3-4.7.12 &&       pyenv global miniconda3-4.7.12 &&       curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 - &&       git clone https://github.com/wasicse/Dispredict3.0.git:
0.171 
0.171 ERROR: The binary distribution of Miniconda is not available for Linux-aarch64.
0.172 
------
Dockerfile:14
--------------------
  13 |     ENV PYTHON_VERSION=miniconda3-4.7.12
  14 | >>> RUN pyenv install ${PYTHON_VERSION} && \
  15 | >>>       pyenv global ${PYTHON_VERSION} && \      
  16 | >>>       curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 - && \
  17 | >>>       git clone https://github.com/wasicse/Dispredict3.0.git
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pyenv install ${PYTHON_VERSION} &&       pyenv global ${PYTHON_VERSION} &&       curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 - &&       git clone https://github.com/wasicse/Dispredict3.0.git" did not complete successfully: exit code: 1`

I can't use the webserver because I need to run it for many proteins :/

Thanks for your help!

**Comment by wasicse** [comment]
Yes. The problem is related to the system architecture.
